services:
  build-fhir-profiles-base:
    image: ghcr.io/cybernop/build-fhir-profiles:base
    build:
      target: base-ubuntu
      args:
        - FIRELY_TERMINAL_VERSION=3.1.0

  build-fhir-profiles:
    image: ghcr.io/cybernop/build-fhir-profiles:latest
    build:
      args:
        - OS_BASE=ubuntu
        - SUSHI_VERSION=3.11.0
