services:
  base-ubuntu:
    image: ghcr.io/cybernop/build-fhir-profiles:base-ubuntu
    build:
      target: base-ubuntu

  latest-ubuntu:
    image: ghcr.io/cybernop/build-fhir-profiles:latest-ubuntu
    build:
      args:
        - OS_BASE=ubuntu
        - SUSHI_VERSION=3.11.0
